/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_llmengine_free: (a: number, b: number) => void;
export const initWgpuDevice: () => any;
export const llmengine_appendModelShard: (a: number, b: number, c: number) => void;
export const llmengine_exportKvImage: (a: number, b: number, c: number, d: number, e: number) => any;
export const llmengine_importKvImage: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const llmengine_info: (a: number) => [number, number];
export const llmengine_load: (a: number, b: number, c: number, d: number, e: number, f: any) => any;
export const llmengine_new: () => number;
export const llmengine_prefixInputs: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const llmengine_prefixKey: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const llmengine_provideToolResults: (a: number, b: number, c: number) => any;
export const llmengine_reset: (a: number) => void;
export const llmengine_setPrefillKernel: (a: number, b: number, c: number) => void;
export const llmengine_setSystemPrompt: (a: number, b: number, c: number) => void;
export const llmengine_start: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const start: () => void;
export const wasm_bindgen__convert__closures_____invoke__h2d808c2d349e4bb9: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h39f7e6a28896bbe3: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h453dd913ed002526: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
